### ISSUE TITLE
Outdated runtime

### ISSUE THREAD

**Issue by paluigi** [flathub/com.emqx.MQTTX#19]
Hello, I get the following message when I update my flatpaks:

```
Info: org.freedesktop.Platform//21.08 is end-of-life, with reason:
   org.freedesktop.Platform 21.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Applications using this runtime:
   com.emqx.MQTTX
```
Is there any plan or timeline to update the runtime?
Thanks

**Comment by zachsmith** [comment]
I opened https://github.com/flathub/com.emqx.MQTTX/pull/20 to address this. Feel free to test with `flatpak install --user https://dl.flathub.org/build-repo/57815/com.emqx.MQTTX.flatpakref`

**Comment by djfjeff** [comment]
The issue is still present, is there any plan to ship an update soon to replace the outdated runtime? Thanks!

**Comment by razzeee** [comment]
Should be fixed (in the next hours)
