### ISSUE TITLE
All settings/configuration lost on restart

### ISSUE THREAD

**Issue by daenney** [flathub/com.emqx.MQTTX#6]
Every time I change a setting, create a collection or a connection and then restart the app everything gets lost. It's like it starts with a blank slate every time.

**Comment by pineapplehunter** [comment]
I had the same issue, and found out that the connections are stored in a database in `~/.config/MQTTX`.
This could be solved by setting a `--persist=.config/MQTTX` so I think I'll make a pull request for that.

For now, we can install Flatseal and set `.config/MQTTX` on persist, or maybe set access to your home dir (I have not tested it).
